import Head from 'next/head';
import Link from 'next/link';
import ProductItem from '../components/ProductItem';
import data from '../../utils/dataitem';

export default function Home({ title }) {
  // return <Layout title="HomePage">homePage</Layout>;

  return (
    <>
      <Head>
        <title>{title ? title + '-Amazona' : 'Amazon'}</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="#" />
      </Head>
      <div class="flex min-h-screen flex-col justify-between ">
        <header>
          <nav class="flex h-12 justify-between shadow-md px-4 items-center">
            <Link href="/" class=" text-lg font-bold ">
              Logo
            </Link>
            <div>
              <Link href="/cart" className="p-2">
                Cart
              </Link>
              <Link href="/login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main>
          {/* <div className="grid grid-cols-1 gap-4 md:grid-cols-3 lg:grid-4">
            {data.products.map((product) => (
              <ProductItem product={product} key={product.slug} />
            ))}
          </div> */}
        </main>
        <footer className="flex  justify-center items-center h-10 shadow-inner">
          Footer
        </footer>
      </div>
    </>
  );
}
