import Image from 'next/image';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="#" />
      </Head>
      <h1 className="text-3xl font-bold">Next Tailwind Amazon</h1>
    </div>
  );
}
